apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "srslte.fullname" . }}
  labels:
{{ include "srslte.labels.standard" . | nindent 4 }}
data:
  gnb_zmq.yaml: |
{{ tpl (.Files.Get "resources/gnb_zmq.yaml") . | indent 4 }}
