#GIN_MODE: release
INTERFACE_NAME: lo
XDP_ATTACH_MODE: generic
API_ADDRESS: ":8081"
PFCP_ADDRESS: ":8805"
METRICS_ADDRESS: ":9091"
FEATURE_FTUP: true
FEATURE_UEIP: true
TEID_POOL: 65000
IP_POOL: "10.20.0.100/16"
PFCP_NODE_ID: "172.20.0.100"
N3_ADDRESS: "172.20.0.100"