definitions:
  main.BpfMapProgArrayMember:
    properties:
      duration:
        type: integer
      duration_enabled:
        type: boolean
      fd:
        type: integer
      id:
        type: integer
      name:
        type: string
      run_count:
        type: integer
      run_count_enabled:
        type: boolean
    type: object
  main.FarInfo:
    properties:
      action:
        type: integer
      localIP:
        type: integer
      outerHeaderCreation:
        type: integer
      remoteIP:
        type: integer
      teid:
        type: integer
    type: object
  main.NodeAssociation:
    properties:
      addr:
        type: string
      id:
        type: string
      nextSessionID:
        type: integer
      sessions:
        $ref: '#/definitions/main.SessionMap'
    type: object
  main.NodeAssociationMap:
    additionalProperties:
      $ref: '#/definitions/main.NodeAssociation'
    type: object
  main.PdrInfo:
    properties:
      farId:
        type: integer
      outerHeaderRemoval:
        type: integer
      qerId:
        type: integer
    type: object
  main.QerInfo:
    properties:
      gateStatusDL:
        type: integer
      gateStatusUL:
        type: integer
      maxBitrateDL:
        type: integer
      maxBitrateUL:
        type: integer
      qfi:
        type: integer
      startDL:
        type: integer
      startUL:
        type: integer
    type: object
  main.QerMapElement:
    properties:
      gate_status_dl:
        type: integer
      gate_status_ul:
        type: integer
      id:
        type: integer
      max_bitrate_dl:
        type: integer
      max_bitrate_ul:
        type: integer
      qfi:
        type: integer
    type: object
  main.SPDRInfo:
    properties:
      ipv4:
        items:
          type: integer
        type: array
      pdrInfo:
        $ref: '#/definitions/main.PdrInfo'
      teid:
        type: integer
    type: object
  main.Session:
    properties:
      downlinkPDRs:
        additionalProperties:
          $ref: '#/definitions/main.SPDRInfo'
        type: object
      fars:
        additionalProperties:
          $ref: '#/definitions/main.FarInfo'
        type: object
      localSEID:
        type: integer
      qers:
        additionalProperties:
          $ref: '#/definitions/main.QerInfo'
        type: object
      remoteSEID:
        type: integer
      uplinkPDRs:
        additionalProperties:
          $ref: '#/definitions/main.SPDRInfo'
        type: object
    type: object
  main.SessionMap:
    additionalProperties:
      $ref: '#/definitions/main.Session'
    type: object
  main.UpfConfig:
    properties:
      apiAddress:
        type: string
      interfaceName:
        items:
          type: string
        type: array
      metricsAddress:
        type: string
      n3Address:
        type: string
      pfcpAddress:
        type: string
      pfcpNodeId:
        type: string
      xdpattachMode:
        enum:
        - generic
        - native
        - offload
        type: string
    type: object
  main.XdpStats:
    properties:
      aborted:
        type: integer
      drop:
        type: integer
      pass:
        type: integer
      redirect:
        type: integer
      tx:
        type: integer
    type: object
info:
  contact: {}
paths:
  /config:
    get:
      description: Display configuration
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.UpfConfig'
      summary: Display configuration
      tags:
      - Configuration
  /pfcp_associations:
    get:
      description: List PFCP associations
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.NodeAssociationMap'
      summary: List PFCP associations
      tags:
      - PFCP
  /qer_map:
    get:
      description: List QER map content
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.QerMapElement'
            type: array
      summary: List QER map content
      tags:
      - QER
  /upf_pipeline:
    get:
      description: List UPF pipeline
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.BpfMapProgArrayMember'
            type: array
      summary: List UPF pipeline
      tags:
      - UPF
  /xdp_stats:
    get:
      description: Display XDP statistics
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.XdpStats'
      summary: Display XDP statistics
      tags:
      - XDP
swagger: "2.0"
