version: '3.8'

services:

  eupf:
    image: ghcr.io/edgecomllc/eupf:0.4.1
    privileged: true
    volumes:
      - /sys/fs/bpf:/sys/fs/bpf
    environment:
      GIN_MODE: release
      UPF_INTERFACE_NAME: eth0
      UPF_XDP_ATTACH_MODE: generic
      UPF_API_ADDRESS: ":8081"
      UPF_PFCP_ADDRESS: ":8805"
      UPF_METRICS_ADDRESS: ":9091"
      UPF_PFCP_NODE_ID: "172.20.0.100"
      UPF_N3_ADDRESS: "172.20.0.100"
    ulimits:
      memlock: -1
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      open5gs-main:
        ipv4_address: 172.20.0.100
    sysctls:
      - net.ipv4.conf.all.forwarding=1

  eupf-routes:
    image: praqma/network-multitool:c3d4e04
    network_mode: host
    privileged: true
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - |
        ip ro add 10.46.0.0/16 via 172.20.0.100
        echo "done"
        tail -f /dev/null

networks:
  open5gs-main:
    external: true
