---
apiVersion: crd.projectcalico.org/v1
kind: BGPPeer
metadata:
  name: eupf-10-45-0-0
spec:
  nodeSelector: all()
  peerIP: 10.233.64.1
  asNumber: 65000
---
apiVersion: crd.projectcalico.org/v1
kind: BGPConfiguration
metadata:
  creationTimestamp: null
  name: default
spec:
  asNumber: 64512
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: true
