apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oai-gnb.fullname" . }}
  labels:
    {{- include "oai-gnb.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  gnb.conf.tmpl: |
{{ (.Files.Get "resources/gnb.conf.tmpl") | indent 4 }}
