apiVersion: v1
appVersion: "23.5.0 (5e6f50a20)"
description: >
  SRS5G gnodeb + ue.
home: https://github.com/Gradiant/charts
sources:
  - https://github.com/Gradiant/openverso-charts/tree/fe676f2a30606c2ce51525897f89f625d299af1a/charts/srs-lte
  - https://github.com/srsLTE/srsLTE
  - https://gradiant.github.io/openverso-charts/open5gs-srslte.html
icon: https://docs.srsran.com/en/latest/_static/logo.png
maintainers:
- email: 
  name: PapaySail
name: srs-5g
version: 0.1.3
keywords:
  - 5G
  - gnodeb
