apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - all.yaml

patches:
  - path: patch_rm_default_route_from_nad.yaml
    target: 
      kind: NetworkAttachmentDefinition
      name: n[23]network-ueransim.*