apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: n2-ueransim1
spec:
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "ipvlan",
          "capabilities": { "ips": true },
          "master": "ens3",
          "mode": "l2",
          "ipam": {
            "type": "static"
          }
        }
      ]
    }'