apiVersion: v1
kind: ConfigMap
metadata:
  name: smf3-open5gs-smf
  labels:
    app.kubernetes.io/name: open5gs-smf
    helm.sh/chart: open5gs-smf-2.0.10
    app.kubernetes.io/instance: smf2
    app.kubernetes.io/managed-by: Helm
data:
  smf.yaml: |
    logger:
      level: info
    parameter: {}
    sbi:
      server:
        no_tls: true
      client:
        no_tls: true
    smf:
      sbi:
        - dev: "eth0"
          port: 7777
      pfcp:
        - dev: "eth0"
          port: 8805
      gtpc:
        - dev: "eth0"
          port: 2123
      gtpu:
        - dev: "eth0"
          port: 2152
      subnet:
        -
          addr: 10.43.0.1/16
          dnn: internet
        -
          addr: 2001:db83:cafe::1/48
          dnn: internet
      dns:
        -
          8.8.8.8
        -
          8.8.4.4
        -
          2001:4860:4860::8888
        -
          2001:4860:4860::8844
      mtu: 1400
      info:
        - s_nssai:
            - sst: 1
              sd: 333333
              dnn:
                - internet
          tai:
            - plmn_id:
                mcc: 999
                mnc: 70
              tac: 1
    nrf:
      sbi:
        - name: open5gs-nrf-sbi
          port: 7777
    upf:
      pfcp:
        - name: eupf3
          port: 8805
    