apiVersion: v2
name: universal-chart
version: 0.0.1
appVersion: autoupdate
description: universal Helm chart for deploy your apps to Kubernetes
icon: https://avatars.githubusercontent.com/u/119618995?s=200&v=4
