apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oai-nr-ue.fullname" . }}
  labels:
    {{- include "oai-nr-ue.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  ue.conf.tmpl: |
{{ (.Files.Get "resources/ue.conf.tmpl") | indent 4 }}
