// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injection

import (
	"github.com/edgecomllc/eupf/cli/config"
	"github.com/edgecomllc/eupf/cli/eupf/delivery/cli"
	"github.com/edgecomllc/eupf/cli/eupf/repository/http"
	"github.com/edgecomllc/eupf/cli/eupf/usecase"
)

// Injectors from wire.go:

func InitEupfCLI(baseURL string, cfg *config.Config) *cli.CLI {
	eupfRepository := http.NewEupfHttpRepository(baseURL)
	eupfUseCase := usecase.NewEupf(eupfRepository, cfg)
	cliCLI := cli.NewCLI(eupfUseCase)
	return cliCLI
}
