{
 "title": "5G core / eUPF",
 "tags": [ "UPF" ],
 "time": { "from": "2023-03-23T17:44:34.238Z", "to": "2023-03-23T18:05:10.882Z" },
 "templating": {
  "list": [
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "title": "N3 users traffic XDP packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "XDP packets rate per sec",
     "type": "timeseries",
     "description": "XDP packets rate altogether",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(label_join({__name__=~\"upf_xdp_.*\", job=~\"eupf.*\"}, \"nname\", \",\", \"__name__\",\"instance\")[$__rate_interval:1s])",
       "legendFormat": "{{nname}}"
      }
     ]
    },
    {
     "title": "XDP packets drop rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(upf_xdp_aborted{job=~\"eupf.*\"}[$__rate_interval])",
       "legendFormat": "upf_xdp_aborted"
      },
      {
       "expr": "rate(upf_xdp_drop{job=~\"eupf.*\"}[$__rate_interval])",
       "legendFormat": "upf_xdp_drop"
      }
     ]
    },
    {
     "title": "XDP packets total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "pkts" } },
     "targets": [
      {
       "expr": "{__name__=~\"upf_xdp_.*\", job=~\"eupf.*\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    }
   ]
  },
  { "title": "N4 PFCP request counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Success requests rate per sec",
   "type": "timeseries",
   "description": "The counts per sec of successful session requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(label_join({__name__=~\"upf_.*_success\", job=~\"eupf.*\"}, \"nname\", \",\", \"__name__\",\"instance\")[$__rate_interval:1s])",
     "legendFormat": "{{nname}}"
    }
   ]
  },
  {
   "title": "Rejected requests rate per sec",
   "type": "timeseries",
   "description": "The counts per sec of rejeted session requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(label_join({__name__=~\"upf_.*_reject\", job=~\"eupf.*\"}, \"nname\", \",\", \"__name__\",\"instance\")[$__rate_interval:1s])",
     "legendFormat": "{{nname}}"
    }
   ]
  },
  {
   "title": "Success requests total altogether",
   "type": "timeseries",
   "description": "The total number of successful session requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{__name__=~\"upf_.*_success\", job=~\"eupf.*\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Rejected requests total altogether",
   "type": "timeseries",
   "description": "The total number of rejected session requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{__name__=~\"upf_.*_reject\", job=~\"eupf.*\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "eUPF metrics altogether",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics total altogether",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{__name__=~\"upf_.*\", job=~\"eupf.*\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    }
   ]
  }
 ]
}