{
 "title": "5G core / eUPF",
 "tags": [ "UPF" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "title": "N3 users traffic packets statistics summary for instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Sum rx packets rate per sec",
   "type": "timeseries",
   "description": "eUPF users rx packets rate summary by instances, stacked by layers 3&4",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(label_join(sum by(__name__) ({__name__=~\"upf_rx_.*\"}), \"nname\", \",\", \"__name__\")[$__rate_interval:1s])",
     "legendFormat": "{{nname}}"
    },
    {
     "expr": "sum by(packet_type) (rate(upf_rx[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "N3 users traffic packets XDP action summary for instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "XDP actions rate per sec",
   "type": "timeseries",
   "description": "XDP actions rate altogether",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(label_join(sum by(__name__) ({__name__=~\"upf_xdp_.*\"}), \"nname\", \",\", \"__name__\")[$__rate_interval:1s])",
     "legendFormat": "{{nname}}"
    }
   ]
  },
  {
   "title": "XDP actions rate to drop packets ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(__name__) (rate(upf_xdp_aborted[$__rate_interval]))",
     "legendFormat": "upf_xdp_aborted"
    },
    {
     "expr": "sum by(__name__) (rate(upf_xdp_drop{job=~\"eupf.*\"}[$__rate_interval]))",
     "legendFormat": "upf_xdp_drop"
    }
   ]
  },
  {
   "title": "XDP actions total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pkts" } },
   "targets": [
    {
     "expr": "sum by(__name__) ({__name__=~\"upf_xdp_.*\"})",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "N4 PFCP request counters summary for instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "PFCP messages rate per sec",
     "type": "timeseries",
     "description": "The counts per sec of upf_pfcp_rx/tx The  number of PFCP messages\n//successful session requests",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(label_join(sum by(__name__) ({__name__=~\"upf_.*_success\"}), \"nname\", \",\", \"__name__\")[$__rate_interval:1s])",
       "legendFormat": "{{nname}}"
      },
      {
       "expr": "sum by(message_name) (rate(upf_pfcp_rx[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(message_name) (rate(upf_pfcp_tx[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rejected requests rate per sec",
     "type": "timeseries",
     "description": "The counts per sec of upf_pfcp_rx_errors number of received PFCP messages with cause code.\nrejeted session requests",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(label_join(sum by(__name__) ({__name__=~\"upf_.*_reject\"}), \"nname\", \",\", \"__name__\")[$__rate_interval:1s])",
       "legendFormat": "{{nname}}"
      },
      {
       "expr": "rate(sum by(cause_code, message_name) (upf_pfcp_rx_errors)[$__rate_interval:1s])",
       "legendFormat": "{{nname}}"
      }
     ]
    },
    {
     "title": "upf_pfcp_rx/tx The total number of PFCP messages total // Success requests total altogether",
     "type": "timeseries",
     "description": "upf_pfcp_rx The total number of received PFCP messages\nThe total number of transmitted PFCP messages\nThe total number of successful session requests",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(__name__) ({__name__=~\"upf_.*_success\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(message_name) (upf_pfcp_rx)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(message_name) (upf_pfcp_tx)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "upf_pfcp_rx_errors The total number of received PFCP messages with cause code //Rejected requests total altogether",
     "type": "timeseries",
     "description": "upf_pfcp_rx_errors The total number of received PFCP messages with cause code\nThe total number of rejected session requests",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(__name__) ({__name__=~\"upf_.*_reject\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(cause_code, message_name) (upf_pfcp_rx_errors)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Duration of the PFCP message processing",
     "type": "timeseries",
     "description": "pfcp_upf_pfcp_rx_latency Duration of the PFCP message processing, Microseconds",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "sum by(message_type, quantile) (pfcp_upf_pfcp_rx_latency)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(message_type) (rate(pfcp_upf_pfcp_rx_latency_sum[$__rate_interval]))",
       "legendFormat": "{{message_type}} latency_sum rate"
      },
      {
       "expr": "sum by(message_type) (rate(pfcp_upf_pfcp_rx_latency_count[$__rate_interval]))",
       "legendFormat": "{{message_type}} latency_count rate"
      }
     ]
    }
   ]
  },
  {
   "title": "eUPF metrics altogether",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "metrics total altogether",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(__name__) ({__name__=~\"upf_.*\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}