{
 "title": "5G Core / Open5GS sessions",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "title": "AMF",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ran_ue{service=\"open5gs-amf-metrics\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "amf_session{service=\"open5gs-amf-metrics\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "gnb{service=\"open5gs-amf-metrics\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "eUPF sessions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "upf_pfcp_current_sessions", "legendFormat": "PFCP sessions {{service}}" }
   ]
  },
  {
   "title": "SMF",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "ues_active", "legendFormat": "{{__name__}}:: {{job}}" },
    {
     "expr": "fivegs_smffunction_sm_sessionnbr",
     "legendFormat": "sessionNBR::{{job}}:{{snssai}}"
    }
   ]
  }
 ]
}