{
 "title": "UE latency by MTR",
 "description": "*mtr-exporter* periodically executes [mtr] to a given host and provides the measured results as [prometheus] metrics.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "title": "Last Values",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "mtr_report_wrst_gauge", "legendFormat": "__auto" },
    { "expr": "mtr_report_best_gauge", "legendFormat": "{{count}} - {{host}}" },
    { "expr": "mtr_report_loss_gauge", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MTR results description",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 0 },
   "options": {
    "content": "*mtr-exporter* every 60s executes [mtr](https://www.bitwizard.nl/mtr/index.html) to a given `dst` host and provides the\nmeasured results as prometheus metrics.\nEach point is result of 10 requests (`tests`)\n\nLables mean:\n- `count` is a hop number\n- `host` is a hop address"
   }
  },
  {
   "title": "RTT mtr best",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "mtr_report_best_gauge", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RTT mtr worst",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "mtr_report_wrst_gauge", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "traceroute | Over time range",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum_over_time(mtr_report_loss_gauge[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "max_over_time(mtr_report_wrst_gauge[$__range])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}