---

logger:
  level: info

parameter: {}

sbi:
  server:
    no_tls: true
  client:
    no_tls: true

amf:
  sbi:
    - dev: "eth0"
      port: 7777
  ngap:
    - dev: "eth0"
      port: 38412
  metrics:
    addr: 0.0.0.0
    port: 9090
  guami:
    - amf_id:
        region: 2
        set: 1
      plmn_id:
        mcc: "999"
        mnc: "70"
  tai:
    - plmn_id:
        mcc: "999"
        mnc: "70"
      tac:
        - 1
  plmn_support:
    - plmn_id:
        mcc: "999"
        mnc: "70"
      s_nssai:
        - sd: "0x111111"
          sst: 1
        - sd: "0x222222"
          sst: 1
        - sd: "0x333333"
          sst: 1
  network_name:
    full: Gradiant
  amf_name: open5gs-amf

  security:
    integrity_order : [ NIA2, NIA1, NIA0 ]
    ciphering_order : [ NEA0, NEA1, NEA2 ]

nrf:
  sbi:
    - name: open5gs-nrf-sbi
      port: 7777
