logger:
  level: info
parameter: {}

global:
# max:
#   ue: 1024 # The number of UE can be increased depending on memory size.
#    peer: 64

nrf:
  serving: # 5G roaming requires PLMN in NRF
  - plmn_id:
      mcc: 999
      mnc: 70
  sbi:
    server:
    - dev: "eth0"
      port: 7777
