logger:
  level: info
parameter: {}

sbi:
  server:
    no_tls: true
  client:
    no_tls: true

pcf:
  sbi:
    - dev: "eth0"
      port: 7777
  metrics:
    addr: 0.0.0.0
    port: 9090

nrf:
  sbi:
    - name: open5gs-nrf-sbi
      port: 7777
