name: deploy to dev

on:
  workflow_dispatch:

jobs:
  use-build:
    uses: ./.github/workflows/build.yml
  deploy:
    uses: ./.github/workflows/deploy.yml
    name: deploy to dev
    needs: use-build
    with:
      kube_context: "edgecom-dev"
      environment_name: "dev"
      helm_cmd_args: "--wait --timeout 60s --values .deploy/helm/values/dev.yaml --set image.tag=${{ github.sha }}"
    secrets:
      kube_config: ${{ secrets.KUBE_CONFIG_DEV }}
