name: deploy to test

on:
  workflow_dispatch:

jobs:
  use-build:
    uses: ./.github/workflows/build.yml
  deploy:
    uses: ./.github/workflows/deploy.yml
    name: deploy to test
    needs: use-build
    with:
      kube_context: "edgecom-test"
      environment_name: "test"
      helm_cmd_args: "--wait --timeout 60s --values .deploy/helm/values/test.yaml"
    secrets:
      kube_config: ${{ secrets.KUBE_CONFIG_TEST }}
