name: Loadtest

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  robot-loadtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            robotframework
            robotframework-scapylibrary
            robotframework-requests
            robotframework-run-keyword-async

      - name: Raw UPF Presetup
        uses: ./.github/actions/raw-upf-presetup
        id: raw-upf-presetup

      - name: Build
        run: go build -v -o bin/eupf ./cmd

      - name: Run eUPF and sleep
        run: sudo ./bin/eupf &

      - name: Run robot Loadtest
        run: sudo robot -v TCPREPLAY_LIMIT:7000 -v TCPREPLAY_THREADS:1 Loadtest.robot

      - name: Stop eUPF
        run: sudo killall eupf
