name: Loadtest

on:
  workflow_run:
    workflows: [Test]
    types: [completed]

jobs:
  run-robot-loadtest:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
