name: Run tests on pr

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: clang llvm gcc-multilib libbpf-dev

      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.0'
          cache: true

      - name: Generate Go ebpf objects
        run: go generate -v cmd/eupf/ebpf_objects.go

      - name: Build
        run: go build -v -o bin/eupf ./cmd/eupf

      - name: Go vet
        run: go vet ./cmd/eupf

      - name: Test
        run: go test -v -o bin/eupf ./cmd/eupf
