{{- if and .Values.bird.enabled .Values.bird.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eupf.fullname" . }}-bird
  labels:
    {{- include "eupf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.bird.service.type }}
  ports:
    - port: {{ .Values.bird.service.port }}
      targetPort: bgp
      protocol: TCP
      name: bgp
  selector:
    {{- include "eupf.selectorLabels" . | nindent 4 }}
{{- end }}
